name: AKS-and-deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform AKS Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply

      - name: Azure Login
        uses: azure/login@v1
        with:
          # ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          # ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          # ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          # ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # auth-type: service_principal
        run: terraform apply -auto-approve tfplan || terraform apply -auto-approve
        # (First tries applying saved plan; falls back to direct apply if plan not used/saved)

  deploy:
    name: Deploy to AKS
    needs: terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          auth-type: service_principal

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Get AKS credentials
        run: az aks get-credentials -g demo-aks-rg -n demo-aks --overwrite-existing

      - name: Apply Kubernetes manifests
        run: kubectl apply -f deployment/
